### ISSUE TITLE
Is there a way to debug the cc1101 connection ?

### ISSUE THREAD

**Issue by samxplogs** [xitiomet/flipperzero-chat-esp32#2]
Hi I am having now issue with my cc1101 connection.

When connecting the esp32 module to the usb serial connection. I could see

13:28:27.499 -> Websocket Connection: 10.10.10.2
13:32:32.990 -> Websocket Connection: 10.10.10.2
13:34:59.475 -> Websocket Connection: 10.10.10.2
14:15:38.643 -> Websocket Connection: 10.10.10.2
14:15:42.458 -> Websocket Connection: 10.10.10.2
14:17:01.802 -> Websocket Connection: 10.10.10.2
14:17:03.517 -> Websocket Connection: 10.10.10.2
14:22:33.659 -> Websocket Connection: 10.10.10.2
14:55:44.056 -> Websocket Connection: 10.10.10.2
14:55:55.836 -> Websocket Connection: 10.10.10.2

However that's is it, I am not sure if my connection is OK as I am not receiving any message.

I have a module similar to that one.

https://www.alibaba.com/product-detail/Cleqee-2-E07-M1101D-SMA-CC1101_62358264393.html

diagram 
![image](https://user-images.githubusercontent.com/121982000/223161500-a1cf609a-2fd0-4f19-bbd0-f30961ec650b.png)

esp32   cc1101
3v3   1
gnd   2

d23   6
d19   7
d18   5
d5   4

**Comment by xitiomet** [comment]
I'm not sure about the E07-M1101D-SMA module as I've never used one, assuming its identical to the TI-CC1101 it should work with just the SPI connection. I noticed in your circuit diagram you have GDO0 and GDO2 connected. These aren't used at all by the driver.

The connections i listed in the readme are based on (using the VSPI):
![image](https://user-images.githubusercontent.com/120686/223193212-4e5e2582-6154-4a71-afde-bd6f7b39421e.png)

I am unfamiliar with the ESP32 (MCU?) pinout provided in your diagram.

During boot there is a connection check on the CC1101 that should output to the serial console:
https://github.com/xitiomet/flipperzero-chat-esp32/blob/main/flipperzero-chat-esp32.ino#L335

**Comment by samxplogs** [comment]
Hey I realize the issue might comes from my cc1101. Despite it wiring being OK. I did some test with the flipper frequency analyzer and I have to adjust a bit the frequency on the flipper in order to be able to communicate with it. Thanks again for your time helping me here.

**Comment by xitiomet** [comment]
No problem, feedback and questions help me improve the documentation. Were you able to get communication working between the flipper and the chat bridge?

**Comment by samxplogs** [comment]
Yes in the end I managed. I had to had an offset: Let say from the chatting I requested to use 433Mhz, hence I type /freq 433.
However if I start subghz chat 433000000 from the flipper, I will not be able to chat. I had to start with 433075000 to make it work.

Regarding the documentation, it is definitively great. Problem was Problem Exists Between Keyboard And Chair (pebkac) :). I wasn't following the actions correctly on my Windows setup. For people who are using Windows, I suggest to follow this tutorial https://www.mischianti.org/2021/04/06/esp32-integrated-ffat-fat-exfat-filesystem-6/
It really explains step by step how to setup the mkfatfs tool on Arduino IDE.

Last but not least, I really find your idea interested and I like to make a comparaison between the meshtastic concept. I also made a video presentation [here ](https://youtu.be/x6qY3p6Ga5Q) in order to give visibility to your project

**Comment by xitiomet** [comment]
Knowing about the frequency offset is very helpful, i'm thinking of making that an option in the settings to save users from having to remember the offset.

Thank you for the feedback, I am always trying to improve my documentation skills. (haha, pebkac happens to us all) I have had similar problems with mkfatfs not being found by the arduino sdk, I'm glad to know its not just something weird with my setup, I almost always end up having to copying it manually to the right directory.

Lastly thank you very much for the mention in your video, I cant explain how much it means to me that this project was worth your time. I've subscribed to your channel, and look forward to watching more of your videos.

**Comment by srayneau** [comment]
Hello great project, i have all the problems like samxplogs !
New IDE under linux so FFAT errors, offset frequency, but now it's solved thank you for this great tool !

**Comment by gilmarwsr** [comment]
@srayneau and @samxplogs 
I made a pull request to use custom pinout to ESP32 (WROOM/WROVER in my case)

https://github.com/xitiomet/flipperzero-chat-esp32/pull/4
